### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-descriptorgen#10]
Ensure the generator is ready for deployment. Eg. inside a docker?

**Comment by jbonnet** [comment]
@StefanUPB Exactly.

**Comment by stefanbschneider** [comment]
Just added support for deployment inside a docker container serving the web interface using the nginx web server.

**Comment by stefanbschneider** [comment]
I will update the docker deployment after completing the [TANGO CICD workshop](https://git.cs.upb.de/5gtango/generalDiscussions/wikis/cicd-workshop)
