### ISSUE TITLE
Refactor GUI

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-descriptorgen#45]
Either refactor the GUI (eg, using Angular) so other tools can be integrated like validation and packaging.

Or integrate all tools, including the descriptor generator, into the new portal GUI. This is probably the better option.
For this, I need to 
* check the implementation of the portal
* implement the descriptor generation as backend with REST interface (currently under development in tng-sdk-project)

We should not use the exact same portal as for the VnV and the SP but a copy of it, showing some kind of "developer view/mode", which only shows the SDK tools, not the VnV and SP. This way we could still reuse and adjust the portal implementation, have a consistent look and feel, but have separate GUIs for developer and operator.

**Comment by antonroman** [comment]
Just for the record, this is what has been discussed in the SDK Gitter channel:

**For Y1 review:**

- UPB will use their current GUI for the demo. In the demo they are planning to use the  CLI of the validation to validate their descriptors within the service creation process.
- Quobis is adapting the existing GUI from Sonata adding the custom rule support and will show it. We are going to prepare a 2 minutes video to show to the reviewers all the validation features if is  considered convenient and there is time for it.  

**For Y2 review:**

- the tentative plan would be to use the GUI used for 5GTango portal to integrate both the generation and validation of packages and descriptors. They would be shown only in a "developer view" different from the current management view to deal with SP, policies, SLA, V&V, etc. So when the portal is generated with an specific "dev" flag, it will generate the GUI with only the developer services.
- This way we would have a unified GUI and we take advantage of the existing design and modules of the portal (which is developed in Angular 6, btw).  
- Regarding the development of the developer view portal, we (Quobis) could assume it but we could also give a training in case UPB had resources to do it by themselves.
